data_paths:
  name:
    ingest: # Just wireguard settings
      InterfaceName: wg0 # Will default to its order in the build list, if not provided
      PrivateKey: /etc/wireguard/privkey
      Address: 10.198.10.113
      ListenPort: 5891
      peers:
        Name:
            PublicKeys: t1A4mXWKHd2R3zlnDaDoFx/bCTHEz/FP6CK1PpdVzBs= #pubkey for example-wg-priv.txt
            AllowedIPs: 
              - 10.198.10.1/24
            Endpoint: 10.10.10.1:5891
    functions:
      silent:
        tmp: testing

debug:
  order_vlans: true
  verbose: true
