functions:
  router:
    internal_router:
      links:
        - from: 192.168.100.0/24
          to: 192.168.200.0/24
          ip: 192.168.100.1/24
        - from: 192.168.200.0/24
          to: 192.168.100.0/24
          ip: 192.168.200.1/24

data_paths:
  node_one_router:
    ingest: 
      subnet: 192.168.100.0/24
      vlan: 3000
    type: bidirectional
    path:
      - camera
      - internal_router

  node_two_router:
    ingest:
      subnet: 192.168.200.0/24
      vlan: 3001
    type: bidirectional
    path:
      - gpu
      - internal_router

debug:
  order_vlans: true
  verbose: true

